- name: setup catalouge server
  hosts: catalouge
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app
  # Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete catalouge file
    ansible.builtin.file:
      path: /tmp/catalouge.zip
      state: absent

  - name: download catalouge application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalouge-v3.zip
      dest: /tmp/catalouge.zip

  - name: extract catalouge application
    ansible.builtin.unarchive:
      src: /tmp/catalouge.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy catalouge service
    ansible.builtin.copy:
      src: catalouge.service
      dest: /etc/systemd/system/catalouge.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: connnect to mongodb catalouge
    ansible.builtin.command: mongosh mongodb.vamsimln.online --quiet --eval "db.getMongo().getDBNames().indexOf('catalouge')"
    register: catalouge_output

  # - name: evaluate cataalogue database
  #   community.mongodb.mongodb_shell:
  #     login_host: mongodb.daws86s.fun
  #     eval: db.getMongo().getDBNames().indexOf('catalouge')
  #   register: catalouge_output

  # - name: print catalouge output
  #   ansible.builtin.debug:
  #     msg: "{{ catalouge_output }}"

  - name: load products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.vamsimln.online </app/db/master-data.js
    when: catalouge_output.stdout | int < 0

  # - name: start and enable cataalogue
  #   ansible.builtin.service:
  #     name: catalouge
  #     enabled: yes
  #     state: started

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: catalouge
      enabled: true
      state: started
      daemon_reload: true