- name: create ec2 and route53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f 
    sg_id: sg-0efb46bbc7c5d112f
    zone_id: "Z02155239UQ5JEVY7T4S"
    domain_name: "vamsimln.online"
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name:"{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
